// <auto-generated />
using FinalKhushpreetKaur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalKhushpreetKaur.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalKhushpreetKaur.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Project Office"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Sales"
                        });
                });

            modelBuilder.Entity("FinalKhushpreetKaur.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DepartmentID = 1,
                            EmployeeName = "Rachel",
                            JobTitle = "Software Developer"
                        },
                        new
                        {
                            EmployeeID = 2,
                            DepartmentID = 1,
                            EmployeeName = "Ross",
                            JobTitle = "HR Coordinator"
                        },
                        new
                        {
                            EmployeeID = 3,
                            DepartmentID = 2,
                            EmployeeName = "Monica",
                            JobTitle = "Network Technician"
                        },
                        new
                        {
                            EmployeeID = 4,
                            DepartmentID = 3,
                            EmployeeName = "Chandler",
                            JobTitle = "Project Manager"
                        },
                        new
                        {
                            EmployeeID = 5,
                            DepartmentID = 4,
                            EmployeeName = "Phoebe",
                            JobTitle = "Sales Manager"
                        },
                        new
                        {
                            EmployeeID = 6,
                            DepartmentID = 4,
                            EmployeeName = "Joey",
                            JobTitle = "Sales Associate"
                        });
                });

            modelBuilder.Entity("FinalKhushpreetKaur.Models.Employee", b =>
                {
                    b.HasOne("FinalKhushpreetKaur.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FinalKhushpreetKaur.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
